### ISSUE TITLE
GetSunIrradiance method

### ISSUE THREAD

**Issue by tgalaj** [ebruneton/clear-sky-models#3]
I quite do not understand, what _GetSunIrradiance()_ method should exactly calculate. As I know, it is not explicitly told in the articles (or maybe I've omitted something).

Could you tell me what _GetSunIrradiance()_ method should calculate - e.g. what equation?

**Comment by ebruneton** [comment]
This is the direct light received from the Sun (without scattering, reflection on the ground, etc). It is the equivalent of the L_0 term in the paper (L_0 is a radiance, the Sun was treated as a punctual light source in the paper, instead of a disk). See Eq. 9 and the paragraph just after it.

The only atmospheric effect included in this term is the out scattering due to the atmosphere (aka the transmittance), which makes the Sun look more red near the horizon (because the Sun light travels through more atmosphere than when the Sun is at the zenith).
