### ISSUE TITLE
normalization_factor 

### ISSUE THREAD

**Issue by mororo250** [ebruneton/clear-sky-models#5]
Hello, thanks for the great work you have done here.

I'm having a hard time understanding the normalization_factor. Why exactly do you want to normalize the sky irradiance? and where does this 36.0 come from? I would really appreciate any help here.
Number normalization_factor = 36.0 * watt_per_square_meter /
    Integral(atmosphere_.GetSkyIrradiance(0.0 * m, sun_zenith));

https://github.com/ebruneton/clear-sky-models/blob/master/atmosphere/comparisons.cc#L189

**Comment by mororo250** [comment]
I read the paper again and I understood why you normalized the sky irradiance. I would still like to know where does the 36 comes from?
Also, shouldn't you exclude the solar radiance from the multiplication by the normalization factor?

**Comment by ebruneton** [comment]
This code was used to generate the images in Fig. 9 in the paper. As described in Section 13.1, "we scaled the results with a uniform per-model factor, before tone-mapping, so that each model gives the same sky irradiance (indeed, we are not interested in absolute values here)". 36.0 is just an exposure value, it could be moved to the ToneMapping() call a few lines below to make this clearer.

**Comment by mororo250** [comment]
Thanks
